server:
  servlet:
    context-path: /api
  port: 8080
spring:
  application:
    name: yu-picture-backend
  profiles:
    active: local

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_picture
    username: root
    password: 123456
    # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    host: 192.168.211.201  # 你的虚拟机 IP
    port: 6379             # Redis 默认端口
    database: 0            # 默认使用 0 号数据库
    timeout: 5000ms        # 连接超时时间（5秒）
    password: 123456  # <--- 把这行的注释解开，填上密码
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    #开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1 # 逻辑已删除值。可选，默认值为 1
      logic-not-delete-value: 0 # 逻辑未删除值。可选，默认值为 0
#接口文档
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.yupi.yupicturebackend.controller


